### ISSUE TITLE
Create base "clean" architecture

### ISSUE THREAD

**Issue by Babelia13** [AgueSoftguar/MedAlarm#10]
Create the base architecture from the following link: 
https://github.com/googlesamples/android-architecture/tree/todo-mvp-clean/

You can analyze the code above using this diagram:
![img_20161026_094645](https://cloud.githubusercontent.com/assets/5984824/19717647/f3900956-9b61-11e6-8180-d8958c0f9004.jpg)

**Comment by fjaviermo** [comment]
Resolved in #11
