### ISSUE TITLE
Create hook to check if our code follow Coding Standards

### ISSUE THREAD

**Issue by fjaviermo** [AgueSoftguar/MedAlarm#21]
This issue includes the following tasks:
- Create a Git hook to avoid to make a commit without the coding standars.
- Include a checkstyle rules file.
- Include a custom code style file for MedAlarm project.

**Comment by Babelia13** [comment]
The first step is to update the code style file using the new codestyle.xml file:

- Go to Settings/Editor/Code Style/Java
- Click on "Manage" button
- Import the codestyle.xml file

To install the checkstyle plugin in Android Studio, you need to do the following steps:

- Go to Settings/Plugins
- Click on Browse Repositories...
- Browse "CheckStyle" and select "CheckStyle-IDEA" plugin
![checkstyle plugin](https://cloud.githubusercontent.com/assets/5984824/20924824/c0efd8e2-bbb3-11e6-9bb0-3af9d6bd1abb.PNG)
- Click on "Install" button
- Click on "Close" button
- Restart Android Studio

Now, the checkstyle plugin has been installed. We need to add the checkstyle rules file (checkstyle.xml in the root of the project) to be used with the plugin. To do that, you need to do the following steps in Android Studio:

- Go to Settings/Other settings/Checkstyle
- Select "Only Java sources (including tests)" as Scan Scope
- Click on + button on the right side of the Configuration File box
- Type a description. For example "MedAlarm"
- Select the option "Use a local Checkstyle" file and select checkstyle.xml
- Click on "Next" button
- Select the new configuration file and click on "Apply" button
- Close the Settings screen
![select checkstyle](https://cloud.githubusercontent.com/assets/5984824/20924666/fd5c6a6c-bbb2-11e6-8e98-f83292dfec7f.PNG)
- Go to the CheckStyle tab in Android Studio
- Select "MedAlarm" in the "Rules" 
![checkstyle tab](https://cloud.githubusercontent.com/assets/5984824/20924667/fd5c7c6e-bbb2-11e6-8200-c89ed7ef7d27.PNG)
- To start the CheckStyle, press on the "Check Module" button
![checkstyle example](https://cloud.githubusercontent.com/assets/5984824/20924665/fd5b46fa-bbb2-11e6-8859-fe765491fcb8.PNG)
- Resolve style problems!!

The next step is add the pre-commit hook 

- Download the checkstyle.jar library from the following link: https://sourceforge.net/projects/checkstyle/files/checkstyle/
- Unzip this [pre-commit.zip](https://github.com/AgueSoftguar/MedAlarm/files/633760/pre-commit.zip) and paste the pre-commit file in the .git/hooks/ folder for your project
- Modify the pre-commit file to include your own checkstyle.jar file path
- Modify the pre-commit file rights to allow execute it
- Make sure that you have Java 8
- Make a commit an enjoy!

**Comment by fjaviermo** [comment]
Hi @Babelia13 

Great tutorial! :+1:
